CREATE DATABASE IF NOT EXISTS WILEY1;

USE WILEY1;

CREATE TABLE IF NOT EXISTS LOCATIONS (
	LOCATION_ID INT PRIMARY KEY,
    STREET_ADDRESS VARCHAR(40),
    POSTAL_CODE VARCHAR(12),
    CITY VARCHAR(30) NOT NULL,
    STATE_PROVINCE VARCHAR(25),
    COUNTRY_ID CHAR(2)
);

CREATE TABLE IF NOT EXISTS DEPARTMENTS (
	DEPARTMENT_ID INT PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR(30) NOT NULL,
    MANAGER_ID INT,
    LOCATION_ID INT,
    CONSTRAINT LOCATIONID_FK 
		FOREIGN KEY(LOCATION_ID)
        REFERENCES LOCATIONS(LOCATION_ID)
);

CREATE TABLE IF NOT EXISTS JOBS (
	JOB_ID VARCHAR(10) PRIMARY KEY,
    JOB_TITLE VARCHAR(35) NOT NULL,
    MIN_SALARY INT,
    MAX_SALARY INT
);

CREATE TABLE IF NOT EXISTS EMPLOYEES (
	EMPLOYEE_ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR(20),
    LAST_NAME VARCHAR(25) NOT NULL,
    EMAIL VARCHAR(20) NOT NULL,
    PHONE_NUMBER VARCHAR(20),
    HIRE_DATE DATE NOT NULL,
    JOB_ID VARCHAR(10) NOT NULL,
    SALARY DOUBLE,
    COMMISSION_PCT DOUBLE,
    MANAGER_ID INT,
    DEPARTMENT_ID INT,
    CONSTRAINT DEPTID_FK 
		FOREIGN KEY(DEPARTMENT_ID)
        REFERENCES DEPARTMENTS(DEPARTMENT_ID),
	CONSTRAINT JOBID_FK 
		FOREIGN KEY(JOB_ID)
        REFERENCES JOBS(JOB_ID)
);

CREATE TABLE IF NOT EXISTS COUNTRIES (
	COUNTRY_ID CHAR(2) NOT NULL,
    COUNTRY_NAME VARCHAR(40),
    REGION_ID INT
);

CREATE TABLE IF NOT EXISTS JOB_HISTORY (
	EMPLOYEE_ID INT NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    JOB_ID VARCHAR(10) NOT NULL,
    DEPARTMENT_ID INT
);




